# Generated by Django 4.2.4 on 2023-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityclasses',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
