# Generated by Django 4.2.4 on 2023-08-23 00:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('Lawer_name', models.CharField(blank=True, default='', max_length=60)),
                ('case_num', models.IntegerField(blank=True, default='')),
                ('case_duration', models.FloatField(blank=True, default=None, null=True)),
                ('case_cost', models.FloatField(blank=True, default=None, null=True)),
                ('Def_name', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Cases',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='UniversityClasses',
        ),
    ]
