# Generated by Django 4.2.4 on 2023-08-23 01:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_cases_delete_universityclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='University_Campuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('campus', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'University Campuses',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
